lab_4/Models/NewsBoard.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Lab4.Models
{
    public class NewsBoard
    {

        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name = "Registration Number")]
        public string Id { get; set; }


        [Required,StringLength(50),MinLength(3)]
        public string Title { get; set; }

        [DataType(DataType.Currency)]
        [Column(TypeName = "money")]
        public decimal Fee { get; set; }


        public List<Subscription> Subscriptions { get; set; }

        public List<News> News { get; set; }




    }
}

lab_4/Models/ViewModels/NewsBoardViewModel.cs
using Microsoft.CodeAnalysis.Completion;
using System.Text;

namespace Lab4.Models.ViewModels
{
    public class NewsBoardViewModel
    {


        public IEnumerable<Client> Clients { get; set; }


    

        public IEnumerable<NewsBoard> NewsBoards { get; set; }

        public IEnumerable<Subscription> Subscriptions { get; set; }


    }
}

lab_4/Controllers/NewsBoardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lab4.Data;
using Lab4.Models;
using Lab4.Models.ViewModels;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using MessagePack.Formatters;

namespace Lab4.Controllers
{
    public class NewsBoardsController : Controller
    {
        private readonly NewsDbContext _context;

       

        public NewsBoardsController(NewsDbContext context)
        {
            _context = context;
        }

        // GET: NewsBoards
        public async Task<IActionResult> Index()
        {

            var viewModel = new NewsBoardViewModel
            { 
                NewsBoards = await _context.NewsBoards.ToListAsync()

            };
              return View(viewModel);


        }

        // GET: NewsBoards/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.NewsBoards == null)
            {
                return NotFound();
            }

            var newsBoard = await _context.NewsBoards
                .FirstOrDefaultAsync(m => m.Id == id);
            if (newsBoard == null)
            {
                return NotFound();
            }

            return View(newsBoard);
        }

        // GET: NewsBoards/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: NewsBoards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Fee")] NewsBoard newsBoard)
        {
            if (ModelState.IsValid)
            {
                _context.Add(newsBoard);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(newsBoard);
        }

        // GET: NewsBoards/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.NewsBoards == null)
            {
                return NotFound();
            }

            var newsBoard = await _context.NewsBoards.FindAsync(id);
            if (newsBoard == null)
            {
                return NotFound();
            }
            return View(newsBoard);
        }

        // POST: NewsBoards/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Title,Fee")] NewsBoard newsBoard)
        {
            if (id != newsBoard.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(newsBoard);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsBoardExists(newsBoard.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(newsBoard);
        }

        // GET: NewsBoards/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.NewsBoards == null)
            {
                return NotFound();
            }

            var newsBoard = await _context.NewsBoards
                .FirstOrDefaultAsync(m => m.Id == id);
            if (newsBoard == null)
            {
                return NotFound();
            }
            
            var newsList = _context.News.Where(x=>x.NewsBoardID.Equals(id)).Count();

            ViewBag.newsCount = newsList;
            return View(newsBoard);
        }

        // POST: NewsBoards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.NewsBoards == null)
            {
                return Problem("Entity set 'NewsDbContext.NewsBoards'  is null.");
            }
            var newsBoard = await _context.NewsBoards.FindAsync(id);
            if (newsBoard != null)
            {
                _context.NewsBoards.Remove(newsBoard);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



        [HttpGet]
        public async Task<ActionResult> Select(string id)
        {
            if (id == null || _context.NewsBoards == null)
            {
                return NotFound();
            }

            var title = await _context.NewsBoards.FindAsync(id);

            if (title == null)
            {
                return RedirectToAction("Error", "Home");
            }

            var clients = await (from c in _context.Clients
                                 join s in _context.Subscriptions on c.Id equals s.ClientId
                                 join n in _context.NewsBoards on s.NewsBoardId equals n.Id
                                 where n.Title.Equals(title.Title)
                                 select c).ToListAsync();

            // Render the partial view in the Index view
            return PartialView("_Select",clients);
        }


        private bool NewsBoardExists(string id)
        {
          return _context.NewsBoards.Any(e => e.Id == id);
        }
    }
}

lab_4/Views/NewsBoards/Create.cshtml
@model Lab4.Models.NewsBoard

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>NewsBoard</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fee" class="control-label"></label>
                <input asp-for="Fee" class="form-control" />
                <span asp-validation-for="Fee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

lab_4/Views/NewsBoards/Delete.cshtml
@model Lab4.Models.NewsBoard

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

@{

}

@if(ViewBag.newsCount != 0){
    <p>Can not delete when associated with news</p>
}

else{
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NewsBoard</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fee)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
}

lab_4/Views/NewsBoards/Details.cshtml
@model Lab4.Models.NewsBoard

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>NewsBoard</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fee)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

lab_4/Views/NewsBoards/Edit.cshtml
@model Lab4.Models.NewsBoard

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>NewsBoard</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fee" class="control-label"></label>
                <input asp-for="Fee" class="form-control" />
                <span asp-validation-for="Fee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

lab_4/Views/NewsBoards/Index.cshtml
@model Lab4.Models.ViewModels.NewsBoardViewModel

@{
    ViewData["Title"] = "Index";
    
}



<h1>Index</h1>


<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    <a asp-action="Index" asp-controller="Home">Return to Home</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Title
            </th>
            <th>
                Fee
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.NewsBoards)
        {
           

            <tr>
                <td>
                    @Html.DisplayFor(i => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fee)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                    <a href="#" onclick="LoadClients('@item.Id')">Select</a> |
                    <a asp-action="Index" asp-controller="News" asp-route-id="@item.Id">News</a>

                   
                    
                </td>
            </tr>
        }


    </tbody>
</table>


  <div id="clientTable"></div>

  <script type="text/javascript">
  

  function LoadClients(e){

    console.log("Running client when clicked" + e);
    $.ajax({
        
        url: '@Url.Action("Select","NewsBoards")',
        type: "GET",
        data: {id: e},
        success: function (result){
            $("#clientTable").html(result);
        },
        error: function (error){
            console.log(error);
        }
    });
  }
  
  
  </script>
   



   
